"""Add name to rule

Revision ID: 01bc7843d696
Revises: 1107ccb4ee9d
Create Date: 2016-12-21 14:19:54.625710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bc7843d696'
down_revision = '1107ccb4ee9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'name')
    # ### end Alembic commands ###
