"""Add check_name to check

Revision ID: 1107ccb4ee9d
Revises: 
Create Date: 2016-12-21 13:21:10.054511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1107ccb4ee9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('check_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'check_name')
    # ### end Alembic commands ###
