"""empty message

Revision ID: ebbe6de00f7e
Revises: 7e1a254f7dd3
Create Date: 2017-01-17 16:39:02.758433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbe6de00f7e'
down_revision = '7e1a254f7dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('dbname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'dbname')
    # ### end Alembic commands ###
